version: '3'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
    restart: on-failure


  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"