version: '3'

services:

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      -/app/node_modules
      - .:/app


  backend:
    build:
      context: backend
      dockerfile:
    ports:
      -